name: CSD-public
channels:
  - apple
  - conda-forge
dependencies:
  - anyio=3.6.2=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39h02fc5c5_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2022.12.7=h4653dfc_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cffi=1.15.1=py39h7e6b969_3
  - debugpy=1.6.6=py39h23fbdae_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - h5py=3.6.0=nompi_py39hd982b79_100
  - hdf5=1.12.1=nompi_hd9dbc9e_104
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.1.0=pyha770c72_0
  - importlib_metadata=6.1.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - ipykernel=6.15.0=pyh736e0ef_0
  - ipython=8.11.0=pyhd1c38e8_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.4=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter=1.0.0=py39h2804cbe_8
  - jupyter_client=8.0.3=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py39h2804cbe_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.5.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - krb5=1.20.1=h69eda48_0
  - libblas=3.9.0=16_osxarm64_openblas
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=7.88.1=h9049daf_1
  - libcxx=15.0.7=h75e25f2_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=12_2_0_hd922786_31
  - libgfortran5=12.2.0=h0eea778_31
  - liblapack=3.9.0=16_osxarm64_openblas
  - libnghttp2=1.52.0=hae82a92_0
  - libopenblas=0.3.21=openmp_hc731615_3
  - libprotobuf=3.19.4=hccf11d3_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.40.0=h76d750c_0
  - libssh2=1.10.0=h7a5bd25_3
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=15.0.7=h7cfbb63_0
  - markupsafe=2.1.2=py39h02fc5c5_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - mpi=1.0=openmpi
  - mpi4py=3.1.4=py39haddbe1b_0
  - nbclassic=0.5.3=pyhb4ecaf3_3
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.9=pyhd8ed1ab_0
  - nbconvert-core=7.2.9=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.9=pyhd8ed1ab_0
  - nbformat=5.7.3=pyhd8ed1ab_0
  - ncurses=6.3=h07bb92c_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=6.5.3=pyha770c72_0
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - openmpi=4.1.5=h4e676fc_100
  - openssl=3.1.0=h03a7124_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandoc=2.19.2=hce30654_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.0.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.1.1=pyhd8ed1ab_0
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.4=py39h02fc5c5_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py39h02fc5c5_0
  - python=3.9.16=hea58f1e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pyyaml=6.0=py39h02fc5c5_5
  - pyzmq=25.0.1=py39h0553236_0
  - readline=8.1.2=h46ed386_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=67.6.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tensorflow-deps=2.10.0=0
  - terminado=0.17.1=pyhd1c38e8_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - tornado=6.2=py39h02fc5c5_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.5=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h03a7124_4
  - zstd=1.5.2=hf913c23_6
  - pip:
      - absl-py==1.4.0
      - aiofiles==23.1.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - cachetools==5.3.0
      - certifi==2022.12.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cloudpickle==1.3.0
      - cmx==0.0.31
      - contourpy==1.0.7
      - cycler==0.11.0
      - cython==0.29.33
      - decorator==4.4.2
      - dm-control==1.0.10
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - fasteners==0.18
      - flatbuffers==23.3.3
      - fonttools==4.39.2
      - future==0.18.3
      - gast==0.4.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - glfw==2.5.7
      - google-auth==2.16.2
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.51.3
      - gym==0.17.2
      - gymnasium==0.27.1
      - gymnasium-notices==0.0.1
      - gymnasium-robotics==1.2.0
      - h11==0.9.0
      - httpcore==0.11.1
      - httptools==0.5.0
      - httpx==0.15.4
      - imageio==2.26.0
      - imageio-ffmpeg==0.4.8
      - jax-jumpy==1.0.0
      - joblib==1.2.0
      - keras==2.11.0
      - keras-nightly==2.13.0.dev2023031907
      - keras-preprocessing==1.1.2
      - killport==1.2.0
      - kiwisolver==1.4.4
      - labmaze==1.0.6
      - libclang==15.0.6.1
      - lxml==4.9.2
      - markdown==3.4.1
      - matplotlib==3.7.1
      - moviepy==1.0.3
      - mujoco==2.3.2
      - mujoco-py==2.1.2.14
      - multidict==4.7.6
      - numpy==1.23.5
      - numpy-quaternion==2022.4.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pandas==1.5.3
      - pathtools==0.1.2
      - pillow==9.4.0
      - proglog==0.1.10
      - promise==2.3
      - protobuf==3.19.6
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyglet==1.5.0
      - pyopengl==3.1.6
      - pyparsing==3.0.9
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rfc3986==1.5.0
      - rsa==4.9
      - sanic==20.9.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - sentry-sdk==1.17.0
      - setproctitle==1.3.2
      - shortuuid==1.0.11
      - smmap==5.0.0
      - swig==4.1.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-estimator==2.11.0
      - tensorflow-macos==2.11.0
      - tensorflow-metal==0.7.1
      - termcolor==2.2.0
      - threadpoolctl==3.1.0
      - tqdm==4.65.0
      - ujson==5.7.0
      - urllib3==1.26.15
      - uvloop==0.17.0
      - wandb==0.14.0
      - websockets==8.1
      - werkzeug==2.2.3
      - wrapt==1.15.0
prefix: /Users/guyfreund/miniforge3/envs/CSD-public
